# Generated by Django 4.2.7 on 2023-11-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='task',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='task',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
    ]
