# Generated by Django 4.2.7 on 2023-11-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_categorymodel_task_remove_statusmodel_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(null=True, to='task.taskmodel'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='task',
            field=models.ManyToManyField(null=True, to='task.taskmodel'),
        ),
    ]
