# Generated by Django 4.2.7 on 2023-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_categorymodel_task_alter_statusmodel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
    ]
