# Generated by Django 4.2.7 on 2023-11-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_remove_statusmodel_task_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
